[phases.setup]
nixPkgs = ['rustup', 'protobuf', 'tree']

[phases.build]
cmds = ["cargo build --release --bin chatroom-server", "pwd", "tree -L 3"]

[start]
cmd = "pwd && tree -L 3 && ./target/release/chatroom-server"
