[variables]
PORT = '50051'

[phases.setup]
nixPkgs = ['...', 'protobuf']

[phases.build]
cmds = ['cargo build --release', 'cp ./target/release/chatroom-server $out/chatroom-server']

[start]
cmd = '$out/chatroom-server'
