[phases.setup]
nixPkgs = ['...', 'protobuf', 'tree']

[phases.build]
cmds = ["cargo build --release --bin chatroom-server", "pwd", "tree -L 3"]

[start]
cmd = "pwd && ./target/release/chatroom-server"
